changelog:
  categorise:
    - title: Enhancement
      labels:
        - enhancement
    - titles: Bug Fixes
      labels:
        - bug
        - fixes
  exclude:
    labels:
      - dependencies
    authors:
      - dependabot