name: Contexts
on: push
jobs:   
    print:
        runs-on: ubuntu-latest
        steps: 
            - run: echo "${{ github.actor }}"

name: Environment variables
on: push
jobs:
    run:
        runs-on: ubuntu-latest
        env:
            BRANCH: main
        steps:
            - run: echo "${BRANCH}"
            - uses: actions/checkout@v4
        with:
            ref: {{ env.BRANCH }}
                     
