# name: Static analysis
# on: 
#   pull_request:
#     paths: ['.github/workflows/*.yml', '.github/workflows/*.yaml']
# defaults:
#   run:
#     shell: bash
# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true
# jobs:
#   lint:
#     runs-on: ubuntu-latest
#     timeout-minutes: 5
#     steps:
#       - uses: actions/checkout@v4
#       - run: |
#           docker run --rm -v "${pwd}:${pwd}" -w "$(pwd)" rhysd/actionlint:latest

##コード4.9
# name: Auto_cancel
# on: pull_request
# concurrency: 
#    group: ${{ github.workflow }}-${{ github.ref }}
#    cancel-in-progress: true
# jobs:
#   sleep:
#     runs-on: ubuntu-latest
#     steps:
#       - run: sleep 120

##コード5.1
# name: Debug log
# on: push
# jobs:
#   sleep:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "::debug::This is degug log"

##コード5.2
name: Bash tracing
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
         set -x
         date
         hostname
